#
#  MAKEFILE for R-Scripts
#
#  merely a shortcut for longer calls on the command line
#
#  defined targets:
#  * t testing target. Used in-development
#
#

t:
	Rscript usage.R datadir=~/mhh/mhh.busche-it.de/data/ECDA2014/Splits/intra/Proband1/Split4 annotationdir=~/mhh/mhh.busche-it.de/data/manual_annotations/ECDA-Annotations

