#
#  MAKEFILE for R-Scripts
#
#  merely a shortcut for longer calls on the command line
#
#  defined targets:
#  * t testing target. Used in-development
#
#

DATA=/data/mhh/
t:
	Rscript usage.R datadir=$(DATA)/ECDA2014/Splits/intra/Proband1/Split4 annotationdir=$(DATA)/manual_annotations/ECDA-Annotations

